### ISSUE TITLE
OSError: [Errno 2] ENOENT

### ISSUE THREAD

**Issue by thegreenlion42** [kevinmcaleer/ota#6]
I always get this error, tried on ESP32-C3

Updating device...Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "<stdin>", line 10, in Update
  File "ota.py", line 129, in download_and_install_update_if_available
  File "ota.py", line 97, in update_and_reset
OSError: [Errno 2] ENOENT

**Comment by thegreenlion42** [comment]
commented out "os.rename('latest_code.py', self.filename)".
now it doesn't crash and reboots
"Updating device...Restarting device... (don't worry about an error message after this
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021....".
No error messages at all.
